# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_ship_tax_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ship_tax_code',
            field=models.CharField(blank=True, help_text='Tax Code for Argentina, Brazil, Peru (CUIT/CPF/RUC)', max_length=20, verbose_name='Tax Code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_model',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Shipping Models'),
        ),
        migrations.AlterField(
            model_name='orderauthorization',
            name='payment',
            field=models.CharField(blank=True, max_length=25, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='payment',
            field=models.CharField(blank=True, max_length=25, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='orderpaymentfailure',
            name='payment',
            field=models.CharField(blank=True, max_length=25, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='orderpendingpayment',
            name='payment',
            field=models.CharField(blank=True, max_length=25, verbose_name='Payment Method'),
        ),
    ]
