# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_addressbook_tax_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='tax_code',
            field=models.CharField(blank=True, help_text='Tax Code for Argentina, Brazil, Peru (CUIT/CPF/RUC)', max_length=20, verbose_name='Tax Code'),
        ),
    ]
