# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20160408_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryattribute',
            name='languagecode',
            field=models.CharField(blank=True, choices=[(b'en', b'English')], max_length=10, null=True, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='categoryimagetranslation',
            name='languagecode',
            field=models.CharField(choices=[(b'en', b'English')], max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='languagecode',
            field=models.CharField(choices=[(b'en', b'English')], max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='optiongrouptranslation',
            name='languagecode',
            field=models.CharField(choices=[(b'en', b'English')], max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='optiontranslation',
            name='languagecode',
            field=models.CharField(choices=[(b'en', b'English')], max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='languagecode',
            field=models.CharField(blank=True, choices=[(b'en', b'English')], max_length=10, null=True, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='productimagetranslation',
            name='languagecode',
            field=models.CharField(choices=[(b'en', b'English')], max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='languagecode',
            field=models.CharField(choices=[(b'en', b'English')], max_length=10, verbose_name='language'),
        ),
    ]
